baseURL = "localhost:1313"
languageCode = "en-us"
title = "Eldhose John - software engineer specialized in Data"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Eldhose John"
    description_photo = "portfolio.jpg"
    #favicon = "favicon.png"
    #logo = "logo.png"
    email = "eldhosejohn@gmail.com"
    #facebook = "lex.collado"
    twitter = "eldhojohn"
    #dribbble = "alexiscollado"
    linkedin = "https://www.linkedin.com/in/eldho"
    #medium = "ahvccollado"
    github = "eldhosejohn"
    #googlescholar = "https://scholar.google.com/citations?user=XXXXXXXXXXXXXXXXXXXXX=en"

[params.nav]
    enable = false

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Eldhose John, a software engineer specialized in Data."
    hero_right = ["**Currently sharpening data, language and leadership skills. Previously worked as a Senior Software Engineer in Data at SpringRole, Bangalore.**", "Having an experience of 12 years and worked across various verticals and technologies like CRM, Mobile, Web, Travel and now into Data Science, I am passionate about working with small business and startups to help them take advantage of data - by setting up data infrastructure, ETL, reporting, analysis etc. I also founded a travel startup [Authentic Kerala](https://www.authentickerala.com/)  in 2008.", "I am good at Python, SQL, ETL, Bash, Shell, Looker, Tableau, Pandas, AWS Redshift, Google BigQuery, Google Analytics, Google Firebase, AWS Data Pipeline, Kinesis and still learning.", 
    "I have done B.Tech in Computer Science from [Mar Athanasius College of Engineering](http://www.mace.ac.in) under M.G University."]
    resume = "Resume-Eldhose John.pdf"



[params.process]
    enable = false
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = false
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = false
